# Stage 1: Build the Angular project 
FROM node:latest AS build  

# Set working directory in container
WORKDIR /app

# Copy package.json and package-lock.json and install dependencies
COPY package*.json ./ 
RUN npm install --legacy-peer-deps --cache /tmp/npm-cache --prefer-offline

# Copy the rest of the application code and build it
COPY . . 
RUN npm run build --prod

# Stage 2: Run the Angular app using Nginx
FROM nginx:alpine

# Copy the compiled Angular files from the build stage
COPY --from=build /app/dist/restuarant-frontend/browser /usr/share/nginx/html

# Copy a custom Nginx configuration file, if needed
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 to the outside world
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
